
try {
    console.log('good morning');
    throw 'error!!'
    console.log(a * 8);
}
catch {
    console.log('error');
}

console.log('end');


// catch (err) {
//     console.log(err.message);
// }